
spring:
  application:
    name: pgm-articles
  #    DATABASE
  datasource:
    url: jdbc:postgresql://${PGM_ARTICLE_DB_URL:localhost}:${PGM_ARTICLE_DB_PORT:5432}/${PGM_ARTICLES_DB_NAME:pgm-article-db}?current_schema=${PGM_ARTICLE_SCHEMA:pgmarticle}&stringtype=unspecified
    username: ${PGM_ARTICLES_DB_USERNAME:pgm}
    password: ${PGM_ARTICLES_DB_PASSWORD:pgm}
    hikari:
      maximum-pool-size: ${PGM_HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${PGM_HIKARI_MIN_IDLE:5}
      idle-timeout: ${PGM_HIKARI_IDLE_TIMEOUT:30000}
      max-lifetime: ${PGM_HIKARI_MAX_LIFETIME:1800000}
      connection-timeout: ${PGM_HIKARI_CONNECTION_TIMEOUT:30000}
      auto-commit: ${PGM_HIKARI_AUTO_COMMIT:true}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true
        default_schema: ${PGM_ARTICLE_SCHEMA:pgm-article}

  #FLYWAY
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/${PGM_ARTICLES_DB_NAME:pgm-article-db}
    schemas: ${PGM_ARTICLE_SCHEMA:pgmarticle}
    user: ${PGM_ARTICLES_DB_USERNAME:pgm}
    password: ${PGM_ARTICLES_DB_PASSWORD:pgm}
    locations: classpath:db/migration
    validate-on-migrate: true          # Validate migrations on startup


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
server:
  port: ${PGM_ARTICLES_APP_PORT:8888}
